version: '3.5'
services:
  zeo:
    build:
      context: .
    container_name: zeo
    hostname: zeo
    image: realestate
    volumes:
      - /home/bsuttor/buildout.realestate/data/blobstorage:/plone/instance/var/blobstorage
      - /home/bsuttor/buildout.realestate/data/filestorage:/plone/instance/var/filestorage
    command: zeoserver
  instance:
    container_name: instance
    hostname: instance
    image: realestate
    environment:
      - ZEO_ADDRESS=zeo:8080
      - ZEO_HOST=db
      - ZEO_PORT=8100
    links:
      - zeo:db
    ports:
      - 8080:8080
    labels:
      - "traefik.frontend.rule=Host:www.suttor.be;AddPrefix:/VirtualHostBase/https/www.suttor.be/plone/VirtualHostRoot"


networks:
  default:
    external:
      name: proxy
